spring:
  profiles:
    active: local
  security:
    oauth2:
      shostname: https://sso.hocgin.top
      client:
        registration:
          custom:
            client-id: client_example
            client-secret: hocgin
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          custom:
            user-info-uri: ${spring.security.oauth2.shostname}/oauth/user
            authorization-uri: ${spring.security.oauth2.shostname}/oauth/authorize
            token-uri: ${spring.security.oauth2.shostname}/oauth/token
            user-name-attribute: name

boot:
  sso:
    client:
      ignore-urls:
        - /favicon.ico
        - /actuator/**
